### ISSUE TITLE
Logo for the team

### ISSUE THREAD

**Issue by DavidNguyen58** [3-Big-Ones/effects-of-compsci#9]
![A K A](https://github.com/3-Big-Ones/effects-of-compsci/assets/138356579/c51f70dd-0816-47b0-b9e0-a8e459015b3e)
Logo created using Canva. The colours for the word is inspired by RGB colours.

**Comment by DavidNguyen58** [comment]
> looks good! do you have one without a background?

I thought the one we're using having no background

> also i think it's a tiny bit off centre

Alright, I will try to fix it

**Comment by sglre6355** [comment]
Closed by df4e9908c1c3d98d87ccd32192e5d05550f606d8
